---
AWSTemplateFormatVersion: 2010-09-09
Description: Persistence and task role for the ECS service

Resources:

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: read-write-dynamo-table
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Put*'
                - 'dynamodb:Update*'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:Get*'
                - 'dynamodb:List*'
                - 'dynamodb:BatchGetItem'
                - 'dynamodb:DescribeTable'
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SchedulingTable}*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SchedulingTableV2}*"
        - PolicyName: read-templates-bucket
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 's3:Get*'
                - 's3:List*'
              Resource:
                - 'arn:aws:s3:::ovo-comms-templates'
                - 'arn:aws:s3:::ovo-comms-templates/*'
        - PolicyName: read-credstash
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource:
                - !Sub "arn:aws:kms:eu-west-1:${AWS::AccountId}:key/*"
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
              Resource:
                - !Sub "arn:aws:dynamodb:eu-west-1:${AWS::AccountId}:table/credential-store"
        - PolicyName: read-aiven-bucket
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 's3:Get*'
                - 's3:List*'
              Resource:
                - 'arn:aws:s3:::ovo-comms-aiven'
                - 'arn:aws:s3:::ovo-comms-aiven/*'
        - PolicyName: read-template-summary-table
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Get*'
              Resource:
                Fn::ImportValue:
                  TemplateSummaryTableArn # <- Exported from Template manager cloudformation.yml

  SchedulingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: scheduleId
        AttributeType: S
      - AttributeName: customerId
        AttributeType: S
      - AttributeName: commName
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: orchestrationExpiry
        AttributeType: N
      KeySchema:
      - AttributeName: scheduleId
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: customerId-commName-index
        KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: commName
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: status-orchestrationExpiry-index
        KeySchema:
        - AttributeName: status
          KeyType: HASH
        - AttributeName: orchestrationExpiry
          KeyType: RANGE
        Projection:
          ProjectionType: ALL

# Scheduling table with template id

  SchedulingTableV2:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: scheduleId
        AttributeType: S
      - AttributeName: customerId
        AttributeType: S
      - AttributeName: templateId
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: orchestrationExpiry
        AttributeType: N
      KeySchema:
      - AttributeName: scheduleId
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: customerId-templateId-index
        KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: templateId
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: status-orchestrationExpiry-index
        KeySchema:
        - AttributeName: status
          KeyType: HASH
        - AttributeName: orchestrationExpiry
          KeyType: RANGE
        Projection:
          ProjectionType: ALL

