version: 2
jobs:
  build:
    working_directory: ~/comms-orchestration
    machine:
      image: circleci/classic:edge
    steps:
      - checkout

      # Install credstash
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-credstash"
      - run:
          name: Install python-dev, pip
          command: sudo apt-get update && sudo apt-get install -y libpython2.7-dev python-pip
      - run: pip install credstash
      - save_cache:
          key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-credstash"
          paths:
            - /home/circleci/.cache/pip

      - run:
          name: Logn to AWS as circleci seems to ignore the setting
          command: |
            mkdir ~/.aws
            echo "[default]" >> ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
            - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-master"
      - run: sbt test:compile
      - save_cache:
          key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
          paths:
            - /home/circleci/.ivy2
            - /home/circleci/.sbt
            - /home/circleci/.coursier
            - project/target/resolution-cache
            - target/resolution-cache
            # TODO docker image cache?
      - run: sbt testWithDynamo
      - run: sbt servicetest:test
      - store_artifacts:
                path: /home/circleci/comms-orchestration/target/integration-test-logs
      - deploy:
          name: Deploy if master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
              git clone git@github.com:ovotech/comms-ci-scripts
              comms-ci-scripts/publish_docker_image.sh
              comms-ci-scripts/deploy_to_ecs.sh -s orchestration UAT aws/container-definition.json
              git clone git@github.com:ovotech/comms-e2e-tests && cd comms-e2e-tests && sbt test && cd ..
              comms-ci-scripts/deploy_to_ecs.sh -s orchestration PRD aws/container-definition.json
              comms-ci-scripts/send_librato_deployment_event.sh
              comms-ci-scripts/comment_on_last_merged_pr.sh
              comms-ci-scripts/notify_shipit.sh
            fi
      - deploy:
          name: Deploy to UAT only if deploy-to-uat branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "deploy-to-uat" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
              git clone git@github.com:ovotech/comms-ci-scripts
              comms-ci-scripts/publish_docker_image.sh
              comms-ci-scripts/deploy_to_ecs.sh -s orchestration UAT aws/container-definition.json
            fi
experimental:
  notify:
    branches:
      only:
        - master
