version: 2
jobs:
  build:
    working_directory: ~/comms-orchestration
    machine: true
    steps:
      - checkout

      # Install credstash
      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-credstash"
      - run: pip install credstash
      - save_cache:
          key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-credstash"
          paths:
            - /home/circleci/.cache/pip

      - restore_cache:
          keys:
            - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
            - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-master"
      - run: sbt test:compile
      - save_cache:
          key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
          paths:
            - /home/circleci/.ivy2
            - /home/circleci/.sbt
            - /home/circleci/.coursier
            - project/target/resolution-cache
            - target/resolution-cache
            # TODO docker image cache?
      - run: sbt testWithDynamo
      - run: sbt servicetest:test
      - deploy:
          name: Deploy if master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
              git clone git@github.com:ovotech/comms-ci-scripts
              comms-ci-scripts/publish_docker_image.sh
              comms-ci-scripts/deploy_to_ecs.sh -s orchestration UAT aws/container-definition.json
              git clone git@github.com:ovotech/comms-e2e-tests && cd comms-e2e-tests && sbt test && cd ..
              comms-ci-scripts/deploy_to_ecs.sh -s orchestration PRD aws/container-definition.json
              comms-ci-scripts/send_librato_deployment_event.sh
              comms-ci-scripts/comment_on_last_merged_pr.sh
              comms-ci-scripts/notify_shipit.sh
            fi
      - deploy:
          name: Deploy to UAT only if deploy-to-uat branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "deploy-to-uat" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
              git clone git@github.com:ovotech/comms-ci-scripts
              comms-ci-scripts/publish_docker_image.sh
              comms-ci-scripts/deploy_to_ecs.sh -s orchestration UAT aws/container-definition.json
            fi
experimental:
  notify:
    branches:
      only:
        - master
